var searchData=
[
  ['historicoinformacao',['HistoricoInformacao',['../class_historico_informacao.html',1,'HistoricoInformacao'],['../class_historico_informacao.html#ae1817600f1080a9eccade7dca6067a1b',1,'HistoricoInformacao::HistoricoInformacao(int codhistorico, int codinformacao, int codtarefa, string desc, int codutilizador, Data datainsercao, int codtipo, string info)'],['../class_historico_informacao.html#a3efeca40a4ea955a164929699e302e63',1,'HistoricoInformacao::HistoricoInformacao()'],['../class_historico_informacao.html#a1442dd2a0d34c470cebaabdf64cc5c94',1,'HistoricoInformacao::HistoricoInformacao(const HistoricoInformacao &amp;hi)']]],
  ['historicoinformacao_2eh',['HistoricoInformacao.h',['../_historico_informacao_8h.html',1,'']]],
  ['historicoprojecto',['HistoricoProjecto',['../class_historico_projecto.html',1,'HistoricoProjecto'],['../class_historico_projecto.html#aa3c4708c765d65e01f66426e2a2a5b2b',1,'HistoricoProjecto::HistoricoProjecto(int codhistorico, int codprojecto, int nivelimportancia, Data dataInsercao, Data dataFim, string informacao, string nome, int codEstado, int codUtilizador, Data datainicio, int codTipo, string info)'],['../class_historico_projecto.html#aa6dc3f1f3699f6e37a3c3acc322a3209',1,'HistoricoProjecto::HistoricoProjecto()'],['../class_historico_projecto.html#a26e4896fe709c1c5f92394e3af362857',1,'HistoricoProjecto::HistoricoProjecto(const HistoricoProjecto &amp;hp)']]],
  ['historicoprojecto_2eh',['HistoricoProjecto.h',['../_historico_projecto_8h.html',1,'']]],
  ['historicotarefa',['HistoricoTarefa',['../class_historico_tarefa.html',1,'HistoricoTarefa'],['../class_historico_tarefa.html#a1786e5b2678cdc9910c2b6a7f3e74330',1,'HistoricoTarefa::HistoricoTarefa(int codhistorico, int codtarefa, int codprojecto, int codestado, int nivelimportancia, Data datacriacao, Data datafim, string informacao, Data dataestimada, int duracao, string tipo, string titulo, int dependente, int codutilizador, int ncontexto, int delegado, Data datainsercao, int codtipo, string info)'],['../class_historico_tarefa.html#a52e29da81a693f83efaed78f9b0f1fb9',1,'HistoricoTarefa::HistoricoTarefa()'],['../class_historico_tarefa.html#a071695f253833308b60d41e199e5dd61',1,'HistoricoTarefa::HistoricoTarefa(const HistoricoTarefa &amp;ht)']]],
  ['historicotarefa_2eh',['HistoricoTarefa.h',['../_historico_tarefa_8h.html',1,'']]]
];
